import { useEffect, useMemo, useState } from "react";
import { BrainCircuit, Check, ChevronDown, KeyRound, LockKeyhole, Send, Sparkles, X } from "lucide-react";

const clients = ["Luna Reis", "Caio Sol", "Projeto interno"];
type Memory = { notes: string; updatedAt: string };

export function AssistantWidget({ onClose }: { onClose: () => void }) {
  const [message, setMessage] = useState(""); const [client, setClient] = useState("Luna Reis"); const [showConfig, setShowConfig] = useState(false); const [provider, setProvider] = useState("openai"); const [apiKey, setApiKey] = useState(""); const [configStatus, setConfigStatus] = useState("");
  const [memories, setMemories] = useState<Record<string, Memory>>(() => { try { return JSON.parse(localStorage.getItem("duck-client-memories") || "{}"); } catch { return {}; } });
  const [messages, setMessages] = useState([{ from: "duck", text: "Olá, Duck. Estou em modo local e pronto para observar seu processo." }]); const [saved, setSaved] = useState(false); const reply = useMemo(() => "Posso comparar seu fluxo, organizar a próxima entrega ou guardar uma preferência deste cliente. Sem API key, continuo funcionando por regras locais.", []);
  useEffect(() => { setMessages([{ from: "duck", text: memories[client]?.notes || `Contexto de ${client} carregado. O que devemos observar nesta sessão?` }]); setSaved(Boolean(memories[client])); }, [client, memories]);
  const send = () => { const trimmed = message.trim(); if (!trimmed) return; setMessages((current) => [...current, { from: "user", text: trimmed }, { from: "duck", text: reply }]); setMessage(""); };
  const saveMemory = () => { const next = { ...memories, [client]: { notes: message.trim() || `Preferências observadas para ${client}.`, updatedAt: new Date().toISOString() } }; setMemories(next); localStorage.setItem("duck-client-memories", JSON.stringify(next)); setMessage(""); setSaved(true); };
  const validateKey = async () => { try { const response = await fetch("http://127.0.0.1:8765/assistant/config/validate", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ provider, api_key: apiKey }) }); const result = await response.json(); setConfigStatus(result.valid ? "Chave validada; nada foi armazenado." : "Formato inválido."); setApiKey(""); } catch { setConfigStatus("Núcleo local indisponível; o modo offline continua ativo."); } };

  return <aside className="assistant-widget" aria-label="Assistente Duck"><div className="assistant-head"><div className="assistant-face"><span>◡</span><i /></div><div><b>Duck assistente</b><small><span className="status-dot" /> MODO LOCAL · MEMÓRIA ATIVA</small></div><button onClick={onClose} className="icon-button" aria-label="Fechar assistente"><X size={16} /></button></div><label className="assistant-client"><div><small>CONTEXTO INDIVIDUAL</small><select value={client} onChange={(event) => setClient(event.target.value)} aria-label="Cliente ativo">{clients.map((item) => <option key={item}>{item}</option>)}</select></div><ChevronDown size={15} /></label><div className="assistant-messages">{messages.map((item, index) => <div key={`${item.from}-${index}`} className={`assistant-message ${item.from}`}>{item.text}</div>)}</div><div className="memory-note"><BrainCircuit size={16} /><span><b>Memória persistente</b><small>{saved ? `Preferências de ${client} salvas localmente.` : `Adicione uma nota para ${client}.`}</small></span><button onClick={saveMemory} aria-label="Guardar memória">{saved ? <Check size={15} /> : <LockKeyhole size={14} />}</button></div>{showConfig && <div className="api-config"><div><b>IA externa opcional</b><small>A chave é validada pelo núcleo local e nunca é guardada aqui.</small></div><select value={provider} onChange={(event) => setProvider(event.target.value)}><option value="openai">OpenAI</option></select><input type="password" value={apiKey} onChange={(event) => setApiKey(event.target.value)} placeholder="Cole a chave apenas para validar" /><button className="secondary-button" onClick={validateKey}><KeyRound size={14} /> Validar</button>{configStatus && <small className="api-status">{configStatus}</small>}</div>}<div className="assistant-compose"><input value={message} onChange={(event) => setMessage(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter") send(); }} placeholder="Fale com Duck..." /><button onClick={send} aria-label="Enviar mensagem"><Send size={16} /></button></div><button className="assistant-footer assistant-config-button" onClick={() => setShowConfig((value) => !value)}><Sparkles size={12} /> {showConfig ? "Fechar configuração" : "Configurar IA opcional"}</button></aside>;
}
